# Generated by Django 2.0.4 on 2018-05-02 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataDump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomingText', models.CharField(max_length=10000)),
                ('userID', models.CharField(max_length=100)),
                ('recordedTime', models.DateTimeField(verbose_name='date recorded')),
                ('confidenceBye', models.DecimalField(decimal_places=18, max_digits=21, null=True)),
                ('confidenceGreet', models.DecimalField(decimal_places=18, max_digits=21, null=True)),
                ('confidenceLoc', models.DecimalField(decimal_places=18, max_digits=21, null=True)),
                ('confidenceThank', models.DecimalField(decimal_places=18, max_digits=21, null=True)),
                ('messageType', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donatedOn', models.CharField(default=-1, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorLogger',
            fields=[
                ('instanceNumber', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('errorCounter', models.IntegerField(default=-1)),
                ('userID', models.CharField(default='no_user_id', max_length=100, null=True)),
                ('errorPlace', models.CharField(default='dummy!', max_length=100)),
                ('errorMessage', models.CharField(default='unknown error!', max_length=1000, null=True)),
                ('recordedTime', models.DateTimeField(auto_now_add=True)),
                ('errorCode', models.IntegerField(blank=True, default=-1, null=True)),
                ('errorSubCode', models.IntegerField(blank=True, default=-1, null=True)),
                ('errorType', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freshUser', models.BooleanField(default=True)),
                ('getStartedStatus', models.BooleanField(default=False)),
                ('donationStatus', models.BooleanField(default=False)),
                ('informationStatus', models.BooleanField(default=False)),
                ('donationAvailDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('userID', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('facebookUserID', models.CharField(max_length=100, unique=True)),
                ('bloodGroup', models.CharField(blank=True, default=None, max_length=2, null=True)),
                ('mobileNumber', models.CharField(default=-1, max_length=15, null=True)),
                ('mobileVerified', models.BooleanField(default=False)),
                ('homeCity', models.CharField(default=-1, max_length=50, null=True)),
                ('currentCity', models.CharField(default=-1, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userstatus',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_bank.UserTable'),
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_bank.UserTable'),
        ),
    ]
