# Generated by Django 2.0.1 on 2018-01-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('userID', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('donorID', models.CharField(max_length=100, unique=True)),
                ('bloodGroup', models.CharField(max_length=2)),
                ('mobileNumber', models.CharField(default=-1, max_length=15, null=True)),
                ('mobileVerified', models.BooleanField(default=False)),
                ('homeCity', models.CharField(default=-1, max_length=50, null=True)),
                ('currentCity', models.CharField(default=-1, max_length=50, null=True)),
            ],
        ),
    ]
