# Generated by Django 2.0.4 on 2018-05-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='userID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
