# Generated by Django 2.0.4 on 2018-05-05 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0002_auto_20180502_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('userID', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('facebookUserID', models.CharField(max_length=100, unique=True)),
                ('bloodGroup', models.CharField(blank=True, default=None, max_length=2, null=True)),
                ('mobileNumber', models.CharField(default=-1, max_length=15, null=True)),
                ('mobileVerified', models.BooleanField(default=False)),
                ('homeCity', models.CharField(default=-1, max_length=50, null=True)),
                ('currentCity', models.CharField(default=-1, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='donationhistory',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_bank.UserInformation'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_bank.UserInformation'),
        ),
    ]
