# Generated by Django 2.0.4 on 2018-05-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0003_auto_20180505_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='currentCity',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='homeCity',
        ),
    ]
