# Generated by Django 2.0.4 on 2018-05-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0004_auto_20180505_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='location',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
