# Generated by Django 2.0.1 on 2018-01-29 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0004_userstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errorMessage', models.CharField(default='unknown error!', max_length=1000, null=True)),
                ('recordedTime', models.DateTimeField()),
                ('errorCode', models.IntegerField(blank=True, default=-1, null=True)),
                ('errorSubCode', models.IntegerField(blank=True, default=-1, null=True)),
                ('errorType', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_bank.UserTable')),
            ],
        ),
    ]
