# Generated by Django 2.0.1 on 2018-03-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0005_errorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadump',
            name='messageType',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='datadump',
            name='nlpConfidence',
            field=models.DecimalField(decimal_places=18, max_digits=21, null=True),
        ),
        migrations.AddField(
            model_name='datadump',
            name='nlpEntity',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
