# Generated by Django 2.0.4 on 2018-05-08 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0005_auto_20180505_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previousRequest', models.CharField(max_length=20)),
                ('expirationDate', models.DateTimeField(editable=False)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_bank.UserInformation')),
            ],
        ),
    ]
