# Generated by Django 2.0.1 on 2018-03-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0006_auto_20180310_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datadump',
            old_name='nlpConfidence',
            new_name='confidenceBye',
        ),
        migrations.RemoveField(
            model_name='datadump',
            name='nlpEntity',
        ),
        migrations.AddField(
            model_name='datadump',
            name='confidenceGreet',
            field=models.DecimalField(decimal_places=18, max_digits=21, null=True),
        ),
        migrations.AddField(
            model_name='datadump',
            name='confidenceLoc',
            field=models.DecimalField(decimal_places=18, max_digits=21, null=True),
        ),
        migrations.AddField(
            model_name='datadump',
            name='confidenceThank',
            field=models.DecimalField(decimal_places=18, max_digits=21, null=True),
        ),
    ]
