# Generated by Django 2.0.1 on 2018-03-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0008_auto_20180310_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='errorPlace',
            field=models.CharField(default='dummy!', max_length=100),
        ),
    ]
