# Generated by Django 2.0.4 on 2018-05-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0008_auto_20180509_0325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTable',
        ),
    ]
