# Generated by Django 2.0.1 on 2018-03-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0009_errorlog_errorplace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertable',
            old_name='donorID',
            new_name='facebookUserID',
        ),
        migrations.AlterField(
            model_name='usertable',
            name='bloodGroup',
            field=models.CharField(default=None, max_length=2, null=True),
        ),
    ]
