# Generated by Django 2.0.4 on 2018-05-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0009_delete_usertable'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowcontroller',
            name='status',
            field=models.CharField(default='Opened', max_length=20),
        ),
    ]
