# Generated by Django 2.0.1 on 2018-03-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0010_auto_20180311_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='freshUser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='recordedTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='donationAvail',
            field=models.DateField(blank=True),
        ),
    ]
