# Generated by Django 2.0.1 on 2018-03-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0011_auto_20180311_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='bloodGroup',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
