# Generated by Django 2.0.1 on 2018-03-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0012_auto_20180311_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='freshUser',
            field=models.BooleanField(default=True),
        ),
    ]
