# Generated by Django 2.0.4 on 2018-04-30 09:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0014_auto_20180314_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorlog',
            name='id',
        ),
        migrations.AddField(
            model_name='errorlog',
            name='instanceNumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='userID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='blood_bank.UserTable'),
        ),
    ]
