# Generated by Django 2.0.4 on 2018-05-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0015_auto_20180430_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='donationAvailDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
