# Generated by Django 2.0.4 on 2018-05-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0016_auto_20180501_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='errorCounter',
            field=models.IntegerField(default=-1),
        ),
    ]
